/* =========================================================
   TỪ VỰNG — dữ liệu cho trang tu-vung.html

   ĐỊNH DẠNG MỖI MỤC: tiếng Anh → IPA → tiếng Việt → 1 câu minh họa
   Câu minh họa viết ở mức A2: từ đang học thì mới, phần còn lại
   của câu phải là thứ bạn đọc trôi ngay. IPA dùng chuẩn Anh (BrE).

   · core     [en, ipa, vi, ex]
   · IRREGULAR[v1, v2, v3, ipa3, vi, ex]   ipa3 = IPA của cả ba dạng
   · PHRASAL  [pv, vi, sep, ex]            không IPA — xem ghi chú dưới
   · COLLOC   [cụm, vi, ex]                không IPA — xem ghi chú dưới

   Vì sao PHRASAL và COLLOC không có IPA: chúng ghép từ những từ bạn
   đã phát âm được rồi (get + up, meet + deadline). Thứ bạn thật sự
   cần ở đó là CÂU MINH HỌA — nó cho thấy tách được hay không, và
   danh từ nào đi với động từ nào. IPA ở đó chỉ là nhiễu.
   ========================================================= */

const V_SOURCES = [
  { name:'Oxford 3000', tag:'chính', count:'~1.500 từ ở dải B1 + B2',
    why:'Bộ duy nhất gắn nhãn CEFR cho từng từ. Lọc bỏ A1 + A2 là ra đúng phần bạn thiếu. Mỗi từ có IPA, audio Anh/Mỹ và câu ví dụ.',
    url:'oxfordlearnersdictionaries.com/wordlists/oxford3000-5000' },
  { name:'BSL — Business Service List', tag:'bổ trợ', count:'~300–400 từ không trùng Oxford',
    why:'Tiếng Anh công sở. Dùng cho tuần 1, 10, 11 — các tuần chủ đề công việc.',
    url:'eflit.net' },
  { name:'PHaVE List', tag:'phrasal verbs', count:'150 phrasal verb theo tần suất',
    why:'Xếp theo tần suất và chỉ ghi nghĩa phổ biến nhất của mỗi từ — thay vì 8 nghĩa mà bạn không bao giờ dùng 7 trong số đó.',
    url:'tra "PHaVE List Garnier Schmitt"' },
  { name:'Oxford Collocations Dictionary', tag:'collocation', count:'tra theo từ',
    why:'Khi bạn đã biết một từ, tra ở đây để biết từ nào đi cùng nó. Đây là bước biến từ thụ động thành từ chủ động.',
    url:'freecollocation.com' },
];

/* ================= 80 ĐỘNG TỪ BẤT QUY TẮC ================= */
const IRREGULAR = [
  { g:'Nhóm 1 · V1 = V2 = V3', note:'Dễ nhất — không đổi gì. Học 10 từ này trước, xong 1/8 số từ.', items:[
    ['cut','cut','cut','kʌt · kʌt · kʌt','cắt','I cut my finger while cooking.'],
    ['put','put','put','pʊt · pʊt · pʊt','đặt, để','She put the file on my desk.'],
    ['let','let','let','let · let · let','cho phép','They let me leave early.'],
    ['set','set','set','set · set · set','đặt, thiết lập','He set the alarm for six.'],
    ['hit','hit','hit','hɪt · hɪt · hɪt','đánh, va vào','The car hit a tree.'],
    ['cost','cost','cost','kɒst · kɒst · kɒst','có giá là','The laptop cost a lot of money.'],
    ['shut','shut','shut','ʃʌt · ʃʌt · ʃʌt','đóng lại','I shut the door quietly.'],
    ['hurt','hurt','hurt','hɜːt · hɜːt · hɜːt','làm đau','My back hurt after the long drive.'],
    ['read','read','read','riːd · red · red','đọc — viết giống nhau, ĐỌC KHÁC','I read the whole book last night.'],
    ['spread','spread','spread','spred · spred · spred','lan ra, trải ra','The news spread very fast.'],
  ]},
  { g:'Nhóm 2 · V2 = V3', note:'Chỉ cần nhớ 1 dạng cho cả quá khứ và phân từ. Để ý cụm -ought / -aught.', items:[
    ['buy','bought','bought','baɪ · bɔːt · bɔːt','mua','I bought a new keyboard.'],
    ['bring','brought','brought','brɪŋ · brɔːt · brɔːt','mang đến','She brought her laptop to the meeting.'],
    ['think','thought','thought','θɪŋk · θɔːt · θɔːt','nghĩ','I thought the test had passed.'],
    ['catch','caught','caught','kætʃ · kɔːt · kɔːt','bắt, đón','He caught the last bus.'],
    ['teach','taught','taught','tiːtʃ · tɔːt · tɔːt','dạy','She taught me how to use Git.'],
    ['seek','sought','sought','siːk · sɔːt · sɔːt','tìm kiếm','They sought help from an expert.'],
    ['build','built','built','bɪld · bɪlt · bɪlt','xây, dựng','We built the app in three months.'],
    ['send','sent','sent','send · sent · sent','gửi','I sent you the link this morning.'],
    ['spend','spent','spent','spend · spent · spent','tiêu tiền, dành thời gian','I spent two hours on this bug.'],
    ['lend','lent','lent','lend · lent · lent','cho vay','He lent me his charger.'],
    ['feel','felt','felt','fiːl · felt · felt','cảm thấy','I felt tired after the long day.'],
    ['keep','kept','kept','kiːp · kept · kept','giữ, tiếp tục','She kept all the old files.'],
    ['sleep','slept','slept','sliːp · slept · slept','ngủ','I slept only five hours.'],
    ['leave','left','left','liːv · left · left','rời khỏi, để lại','He left the office at seven.'],
    ['lose','lost','lost','luːz · lɒst · lɒst','mất, thua','I lost my notes.'],
    ['mean','meant','meant','miːn · ment · ment','có nghĩa là','I meant to call you yesterday.'],
    ['meet','met','met','miːt · met · met','gặp','We met last year in Hanoi.'],
    ['pay','paid','paid','peɪ · peɪd · peɪd','trả tiền','I paid for the licence.'],
    ['say','said','said','seɪ · sed · sed','nói — said đọc /sed/, KHÔNG phải /seɪd/','She said the same thing.'],
    ['sell','sold','sold','sel · səʊld · səʊld','bán','They sold the old servers.'],
    ['tell','told','told','tel · təʊld · təʊld','kể, bảo','He told me the truth.'],
    ['sit','sat','sat','sɪt · sæt · sæt','ngồi','We sat in the back row.'],
    ['stand','stood','stood','stænd · stʊd · stʊd','đứng','He stood near the door.'],
    ['understand','understood','understood','ˌʌndəˈstænd · ˌʌndəˈstʊd · ˌʌndəˈstʊd','hiểu','I understood the problem at last.'],
    ['find','found','found','faɪnd · faʊnd · faʊnd','tìm thấy','I found the bug in one hour.'],
    ['hold','held','held','həʊld · held · held','giữ, cầm, tổ chức','She held the meeting online.'],
    ['hear','heard','heard','hɪə · hɜːd · hɜːd','nghe thấy','I heard the news this morning.'],
    ['make','made','made','meɪk · meɪd · meɪd','làm, tạo ra','He made a small mistake.'],
    ['have','had','had','hæv · hæd · hæd','có','We had a long meeting.'],
    ['get','got','got','ɡet · ɡɒt · ɡɒt','lấy, trở nên','I got your email yesterday.'],
  ]},
  { g:'Nhóm 3 · V1 = V3', note:'Bẫy hay gặp: I have come — không phải I have came.', items:[
    ['come','came','come','kʌm · keɪm · kʌm','đến','He has come to every meeting.'],
    ['become','became','become','bɪˈkʌm · bɪˈkeɪm · bɪˈkʌm','trở thành','The code has become hard to read.'],
    ['run','ran','run','rʌn · ræn · rʌn','chạy, điều hành','I have run the tests twice.'],
    ['overcome','overcame','overcome','ˌəʊvəˈkʌm · ˌəʊvəˈkeɪm · ˌəʊvəˈkʌm','vượt qua','We have overcome the main problem.'],
  ]},
  { g:'Nhóm 4 · Cả ba khác nhau', note:'Nhóm phải học thuộc thật. Chú ý mẫu i–a–u: begin / began / begun.', items:[
    ['be','was / were','been','biː · wɒz, wɜː · biːn','là, ở','The server was down for an hour.'],
    ['go','went','gone','ɡəʊ · went · ɡɒn','đi','He has gone home already.'],
    ['do','did','done','duː · dɪd · dʌn','làm','I have done my part.'],
    ['see','saw','seen','siː · sɔː · siːn','thấy','I saw the error in the log.'],
    ['eat','ate','eaten','iːt · et · ˈiːtn','ăn','Have you eaten lunch yet?'],
    ['give','gave','given','ɡɪv · ɡeɪv · ˈɡɪvn','cho','She gave me good advice.'],
    ['take','took','taken','teɪk · tʊk · ˈteɪkən','lấy, mất (thời gian)','It took three days to fix.'],
    ['write','wrote','written','raɪt · rəʊt · ˈrɪtn','viết','I have written the tests.'],
    ['speak','spoke','spoken','spiːk · spəʊk · ˈspəʊkən','nói','I spoke to my manager today.'],
    ['break','broke','broken','breɪk · brəʊk · ˈbrəʊkən','làm vỡ, phá','Someone broke the build.'],
    ['choose','chose','chosen','tʃuːz · tʃəʊz · ˈtʃəʊzn','chọn','We chose the simple option.'],
    ['drive','drove','driven','draɪv · drəʊv · ˈdrɪvn','lái xe','She drove to the office.'],
    ['ride','rode','ridden','raɪd · rəʊd · ˈrɪdn','đi (xe đạp), cưỡi','I rode my bike to work.'],
    ['rise','rose','risen','raɪz · rəʊz · ˈrɪzn','tăng lên, mọc','Prices have risen this year.'],
    ['drink','drank','drunk','drɪŋk · dræŋk · drʌŋk','uống','I drank too much coffee.'],
    ['begin','began','begun','bɪˈɡɪn · bɪˈɡæn · bɪˈɡʌn','bắt đầu','The meeting has begun.'],
    ['sing','sang','sung','sɪŋ · sæŋ · sʌŋ','hát','She sang at the party.'],
    ['swim','swam','swum','swɪm · swæm · swʌm','bơi','We swam in the sea.'],
    ['ring','rang','rung','rɪŋ · ræŋ · rʌŋ','reo, gọi điện','The phone rang three times.'],
    ['know','knew','known','nəʊ · njuː · nəʊn','biết','I have known him for years.'],
    ['grow','grew','grown','ɡrəʊ · ɡruː · ɡrəʊn','lớn lên, tăng','The team has grown to ten people.'],
    ['throw','threw','thrown','θrəʊ · θruː · θrəʊn','ném','He threw the old code away.'],
    ['show','showed','shown','ʃəʊ · ʃəʊd · ʃəʊn','cho thấy','She has shown me the new design.'],
    ['fly','flew','flown','flaɪ · fluː · fləʊn','bay','I flew to Da Nang last week.'],
    ['draw','drew','drawn','drɔː · druː · drɔːn','vẽ, rút ra','He drew a simple diagram.'],
    ['wear','wore','worn','weə · wɔː · wɔːn','mặc, đeo','She wore a blue shirt.'],
    ['fall','fell','fallen','fɔːl · fel · ˈfɔːlən','rơi, giảm','The number has fallen by half.'],
    ['forget','forgot','forgotten','fəˈɡet · fəˈɡɒt · fəˈɡɒtn','quên','I forgot to save the file.'],
    ['freeze','froze','frozen','friːz · frəʊz · ˈfrəʊzn','đóng băng, treo máy','The screen froze for a minute.'],
    ['hide','hid','hidden','haɪd · hɪd · ˈhɪdn','trốn, che','He hid the error in a try block.'],
    ['steal','stole','stolen','stiːl · stəʊl · ˈstəʊlən','ăn cắp','Someone stole my bike.'],
    ['wake','woke','woken','weɪk · wəʊk · ˈwəʊkən','thức dậy','I woke up at five.'],
    ['forgive','forgave','forgiven','fəˈɡɪv · fəˈɡeɪv · fəˈɡɪvn','tha thứ','She forgave me for being late.'],
    ['shake','shook','shaken','ʃeɪk · ʃʊk · ˈʃeɪkən','lắc, rung','He shook my hand.'],
    ['tear','tore','torn','teə · tɔː · tɔːn','xé','I tore the paper by mistake.'],
    ['blow','blew','blown','bləʊ · bluː · bləʊn','thổi','The wind blew all night.'],
  ]},
];

/* ================= 60 PHRASAL VERBS =================
   sep = tách được · insep = không tách. Câu minh họa cho thấy rõ điều đó. */
const PHRASAL = [
  { g:'20 phrasal verb công việc', note:'Nhóm bạn dùng nhiều nhất trong Slack và standup.', items:[
    ['hand over','giao lại, chuyển giao','sep','Please hand the project over to Nam.'],
    ['follow up','theo dõi tiếp, hỏi lại','insep','I will follow up next week.'],
    ['sort out','giải quyết, xử lý xong','sep','Can you sort this problem out?'],
    ['carry out','thực hiện, tiến hành','sep','We carried out the plan on Monday.'],
    ['set up','thiết lập, dựng lên','sep','He set the server up in one hour.'],
    ['back up','sao lưu · hỗ trợ ai','sep','Back your files up every day.'],
    ['roll out','triển khai ra diện rộng','sep','We rolled the feature out slowly.'],
    ['figure out','tìm ra, hiểu ra','sep','I figured the problem out at last.'],
    ['work out','tính ra · hoá ra ổn','sep','It worked out well in the end.'],
    ['take over','tiếp quản','sep','She took the project over from me.'],
    ['put off','trì hoãn','sep','Do not put it off again.'],
    ['call off','huỷ bỏ','sep','They called the meeting off.'],
    ['fill in','điền vào (form)','sep','Please fill this form in.'],
    ['hand in','nộp','sep','Hand your report in by Friday.'],
    ['look into','xem xét, điều tra','insep','I will look into the bug today.'],
    ['deal with','xử lý, đối phó','insep','He deals with all the emails.'],
    ['come up with','nghĩ ra, đề xuất','insep','She came up with a good idea.'],
    ['catch up on','làm cho kịp phần bị chậm','insep','I need to catch up on my email.'],
    ['go over','xem lại, rà lại','insep','Let us go over the plan again.'],
    ['break down','hỏng · phân tích ra từng phần','insep','My laptop broke down yesterday.'],
  ]},
  { g:'20 phrasal verb sinh hoạt hằng ngày', note:'Dễ nhất — bạn đã dùng bằng tiếng Việt mỗi ngày rồi.', items:[
    ['get up','thức dậy, ra khỏi giường','insep','I get up at six every day.'],
    ['wake up','tỉnh giấc','sep','The noise woke me up.'],
    ['turn on','bật','sep','Turn the light on, please.'],
    ['turn off','tắt','sep','Please turn your phone off.'],
    ['put on','mặc vào, đeo vào','sep','He put his coat on.'],
    ['take off','cởi ra · máy bay cất cánh','sep','Take your shoes off here.'],
    ['clean up','dọn dẹp','sep','We cleaned the office up.'],
    ['throw away','bỏ đi, ném đi','sep','Do not throw that paper away.'],
    ['run out of','dùng hết, cạn','insep','We ran out of coffee.'],
    ['pick up','lấy lên, đi đón','sep','I will pick you up at eight.'],
    ['drop off','thả xuống, đưa đến','sep','Can you drop me off at the station?'],
    ['get on','lên (xe bus, tàu)','insep','I got on the wrong bus.'],
    ['get off','xuống (xe bus, tàu)','insep','Get off at the next stop.'],
    ['eat out','ăn ngoài, ăn hàng','insep','We eat out on Fridays.'],
    ['stay up','thức khuya','insep','I stayed up until midnight.'],
    ['lie down','nằm xuống','insep','I need to lie down for ten minutes.'],
    ['wash up','rửa bát','insep','He washed up after dinner.'],
    ['try on','thử quần áo','sep','Can I try this shirt on?'],
    ['hang up','cúp máy','insep','She hung up without saying goodbye.'],
    ['look after','chăm sóc, trông','insep','Who looks after the server?'],
  ]},
  { g:'20 phrasal verb giao tiếp', note:'Nhóm cần cho họp và tranh luận — học tuần 15, dùng ở AI voice mỗi T7.', items:[
    ['find out','phát hiện ra','sep','I found out the real reason.'],
    ['point out','chỉ ra, nêu ra','sep','She pointed out my mistake.'],
    ['bring up','nêu lên (một chủ đề)','sep','He brought the problem up in the meeting.'],
    ['speak up','nói to hơn · lên tiếng','insep','Please speak up, I cannot hear you.'],
    ['talk over','thảo luận kỹ','sep','Let us talk this over tomorrow.'],
    ['sum up','tóm lại','sep','To sum up, the plan works.'],
    ['put forward','đề xuất','sep','She put forward a new idea.'],
    ['get across','truyền đạt được ý','sep','I could not get my point across.'],
    ['turn down','từ chối · giảm âm lượng','sep','They turned my request down.'],
    ['turn up','xuất hiện · tăng âm lượng','sep','He turned up an hour late.'],
    ['give up','bỏ, từ bỏ','sep','Do not give up so early.'],
    ['count on','trông cậy vào','insep','You can count on me.'],
    ['look forward to','mong đợi','insep','I look forward to your reply.'],
    ['get along with','hoà thuận với','insep','I get along with my team.'],
    ['make up','bịa ra · làm hoà','sep','He made up an excuse.'],
    ['fall out','cãi nhau, xích mích','insep','They fell out over a small thing.'],
    ['back down','nhượng bộ, rút lại','insep','He backed down after the vote.'],
    ['stand up for','bảo vệ, đứng lên vì','insep','She stood up for her team.'],
    ['go along with','đồng ý theo','insep','I will go along with your plan.'],
    ['sort of','kiểu như (nói giảm nhẹ)','insep','It is sort of working now.'],
  ]},
];

/* ================= 100 COLLOCATION ================= */
const COLLOC = [
  { g:'Deadline & kế hoạch', items:[
    ['meet a deadline','kịp hạn','We met the deadline by one hour.'],
    ['miss a deadline','trễ hạn','He missed the deadline again.'],
    ['set a deadline','đặt hạn','Let us set a deadline for Friday.'],
    ['extend a deadline','gia hạn','They extended the deadline by a week.'],
    ['a tight deadline','hạn gấp','We work well under a tight deadline.'],
    ['meet a target','đạt chỉ tiêu','The team met its target this month.'],
    ['set a goal','đặt mục tiêu','I set a goal of ten words a day.'],
    ['achieve a goal','đạt mục tiêu','She achieved her main goal.'],
    ['reach an agreement','đạt thoả thuận','We reached an agreement quickly.'],
    ['make a plan','lập kế hoạch','Let us make a plan first.'],
    ['draw up a plan','vạch ra kế hoạch','He drew up a plan for the year.'],
    ['stick to a plan','theo đúng kế hoạch','It is hard to stick to a plan.'],
    ['make progress','có tiến triển','I made good progress today.'],
    ['track progress','theo dõi tiến độ','We track progress every week.'],
    ['set a priority','đặt ưu tiên','Set your priorities before you start.'],
    ['top priority','ưu tiên cao nhất','Security is our top priority.'],
    ['allocate resources','phân bổ nguồn lực','We allocate resources every month.'],
    ['estimate effort','ước lượng công sức','It is hard to estimate effort.'],
    ['schedule a task','lên lịch cho việc','I scheduled the task for Monday.'],
    ['fall behind schedule','chậm so với lịch','The project fell behind schedule.'],
  ]},
  { g:'Họp & giao tiếp', items:[
    ['attend a meeting','tham dự họp','I cannot attend the meeting today.'],
    ['hold a meeting','tổ chức họp','We hold a meeting every Monday.'],
    ['schedule a meeting','đặt lịch họp','Can you schedule a meeting for two?'],
    ['cancel a meeting','huỷ họp','They cancelled the meeting.'],
    ['chair a meeting','chủ trì cuộc họp','She chaired the meeting well.'],
    ['raise an issue','nêu một vấn đề','He raised an issue about cost.'],
    ['raise a concern','nêu lo ngại','I want to raise a concern.'],
    ['address a concern','giải quyết lo ngại','The manager addressed my concern.'],
    ['give feedback','đưa nhận xét','Please give feedback on my code.'],
    ['receive feedback','nhận nhận xét','I received useful feedback.'],
    ['ask a question','đặt câu hỏi','May I ask a question?'],
    ['make a point','nêu một luận điểm','She made a good point.'],
    ['share an idea','chia sẻ ý tưởng','I would like to share an idea.'],
    ['reach a conclusion','đi đến kết luận','We reached a clear conclusion.'],
    ['take minutes','ghi biên bản','Who will take the minutes?'],
    ['follow an agenda','theo chương trình họp','Let us follow the agenda.'],
    ['send an update','gửi cập nhật','I will send an update tonight.'],
    ['keep somebody informed','giữ ai đó được thông báo','Please keep me informed.'],
    ['get in touch','liên lạc','Get in touch if you need help.'],
    ['speak on behalf of','nói thay cho','I speak on behalf of my team.'],
  ]},
  { g:'Vấn đề & quyết định', items:[
    ['solve a problem','giải quyết vấn đề','We solved the problem in one day.'],
    ['cause a problem','gây ra vấn đề','The update caused a problem.'],
    ['face a problem','đối mặt vấn đề','We face a serious problem.'],
    ['identify a problem','xác định vấn đề','First, identify the problem.'],
    ['fix a bug','sửa lỗi','I fixed the bug this morning.'],
    ['report a bug','báo lỗi','Please report any bug you find.'],
    ['make a decision','ra quyết định','We must make a decision today.'],
    ['postpone a decision','hoãn quyết định','They postponed the decision.'],
    ['weigh the options','cân nhắc các lựa chọn','Let us weigh the options first.'],
    ['take a risk','chấp nhận rủi ro','We took a small risk.'],
    ['avoid a risk','tránh rủi ro','We can avoid this risk easily.'],
    ['assess a risk','đánh giá rủi ro','We assess the risk before we ship.'],
    ['make a mistake','mắc lỗi','Everyone makes mistakes.'],
    ['learn from a mistake','học từ lỗi','I learned from my mistake.'],
    ['find a solution','tìm ra giải pháp','We found a simple solution.'],
    ['propose a solution','đề xuất giải pháp','He proposed a good solution.'],
    ['draw a conclusion','rút ra kết luận','Do not draw a conclusion too early.'],
    ['take responsibility','nhận trách nhiệm','She took responsibility for the error.'],
    ['take action','hành động','We must take action now.'],
    ['run into trouble','gặp rắc rối','The team ran into trouble on day two.'],
  ]},
  { g:'Số liệu & báo cáo', items:[
    ['analyse data','phân tích dữ liệu','We analyse data every week.'],
    ['collect data','thu thập dữ liệu','They collect data from users.'],
    ['present data','trình bày dữ liệu','He presented the data clearly.'],
    ['interpret results','diễn giải kết quả','It is hard to interpret these results.'],
    ['draw attention to','hướng chú ý tới','I want to draw attention to one point.'],
    ['show a trend','cho thấy xu hướng','The chart shows a clear trend.'],
    ['a sharp increase','tăng mạnh','There was a sharp increase in users.'],
    ['a slight decrease','giảm nhẹ','We saw a slight decrease in speed.'],
    ['a significant difference','khác biệt đáng kể','There is a significant difference.'],
    ['account for','chiếm · giải thích cho','Mobile users account for half our traffic.'],
    ['have an impact on','có tác động tới','This will have an impact on speed.'],
    ['play a role in','đóng vai trò trong','Testing plays a big role in quality.'],
    ['carry out research','tiến hành nghiên cứu','We carried out research last year.'],
    ['conduct a survey','thực hiện khảo sát','We conducted a survey of 100 users.'],
    ['provide evidence','cung cấp bằng chứng','The logs provide clear evidence.'],
    ['support a claim','củng cố một nhận định','These numbers support my claim.'],
    ['exceed expectations','vượt mong đợi','The result exceeded expectations.'],
    ['fall short of','không đạt tới','The result fell short of our target.'],
    ['meet requirements','đáp ứng yêu cầu','The app meets all requirements.'],
    ['in the long run','về lâu dài','Tests save time in the long run.'],
  ]},
  { g:'Nghề nghiệp & làm việc nhóm', items:[
    ['apply for a job','ứng tuyển','I applied for a job in Hanoi.'],
    ['get a promotion','được thăng chức','She got a promotion last month.'],
    ['gain experience','tích luỹ kinh nghiệm','I gained a lot of experience there.'],
    ['develop skills','phát triển kỹ năng','I want to develop my writing skills.'],
    ['build a career','xây dựng sự nghiệp','He built a career in five years.'],
    ['join a team','vào một nhóm','I joined the team in March.'],
    ['work as a team','làm việc theo nhóm','We work well as a team.'],
    ['lead a team','dẫn dắt nhóm','She leads a team of six.'],
    ['take on a task','nhận một việc','I took on a difficult task.'],
    ['delegate a task','giao việc cho người khác','A good manager delegates tasks.'],
    ['hand in a report','nộp báo cáo','I handed in my report late.'],
    ['write a report','viết báo cáo','I write a report every month.'],
    ['review code','review code','We review code before we merge.'],
    ['merge a branch','gộp nhánh','I merged the branch this morning.'],
    ['deploy a release','phát hành bản mới','We deploy a release every Friday.'],
    ['meet a client','gặp khách hàng','I met the client on Tuesday.'],
    ['handle a request','xử lý yêu cầu','She handles every request quickly.'],
    ['provide support','cung cấp hỗ trợ','We provide support by email.'],
    ['make a suggestion','đưa ra gợi ý','May I make a suggestion?'],
    ['work under pressure','làm việc dưới áp lực','He works well under pressure.'],
  ]},
];

/* ================= TỪ LÕI CỦA TỪNG CHỦ ĐỀ TUẦN =================
   10 từ mở đầu mỗi chủ đề. Ngân sách thật 50 từ/tuần —
   40 từ còn lại lọc từ Oxford 3000 dải B1 + B2 theo cùng chủ đề. */
const V_THEMES = [
  { w:1, m:1, theme:'công việc văn phòng', src:'Oxford B1 + BSL', items:[
    ['deadline','ˈdedlaɪn','hạn cuối','The deadline is Friday at five.'],
    ['meeting','ˈmiːtɪŋ','cuộc họp','We have a team meeting every Monday.'],
    ['report','rɪˈpɔːt','báo cáo','I sent the report to my manager.'],
    ['task','tɑːsk','nhiệm vụ','This task will take two hours.'],
    ['schedule','ˈʃedjuːl','lịch trình','My schedule is full this week.'],
    ['colleague','ˈkɒliːɡ','đồng nghiệp','My colleague helped me fix the bug.'],
    ['manager','ˈmænɪdʒə','người quản lý','My manager asked for an update.'],
    ['salary','ˈsæləri','lương','The salary is paid on the last day.'],
    ['department','dɪˈpɑːtmənt','bộ phận','She works in the design department.'],
    ['overtime','ˈəʊvətaɪm','làm thêm giờ','I did three hours of overtime.'] ]},
  { w:2, m:1, theme:'địa điểm & di chuyển', src:'Oxford A2–B1', items:[
    ['commute','kəˈmjuːt','đi lại nhà – chỗ làm','My commute takes forty minutes.'],
    ['traffic','ˈtræfɪk','giao thông','The traffic is bad in the morning.'],
    ['route','ruːt','lộ trình','I take a different route to work now.'],
    ['distance','ˈdɪstəns','khoảng cách','The distance from home to work is 8 km.'],
    ['neighbourhood','ˈneɪbəhʊd','khu phố','I live in a quiet neighbourhood.'],
    ['downtown','ˌdaʊnˈtaʊn','trung tâm','The office is downtown.'],
    ['suburb','ˈsʌbɜːb','ngoại ô','They moved to a suburb outside the city.'],
    ['crossroads','ˈkrɒsrəʊdz','ngã tư','Turn left at the next crossroads.'],
    ['lane','leɪn','làn đường','Stay in the right lane.'],
    ['destination','ˌdestɪˈneɪʃn','điểm đến','We arrived at our destination late.'] ]},
  { w:3, m:1, theme:'thói quen & lịch trình', src:'Oxford A2–B1', items:[
    ['routine','ruːˈtiːn','việc thường ngày','My morning routine takes one hour.'],
    ['habit','ˈhæbɪt','thói quen','Reading before bed is a good habit.'],
    ['regularly','ˈreɡjələli','thường xuyên','I go to the gym regularly.'],
    ['occasionally','əˈkeɪʒnəli','đôi khi','I occasionally work at the weekend.'],
    ['rarely','ˈreəli','ít khi','He rarely eats breakfast.'],
    ['timetable','ˈtaɪmteɪbl','thời gian biểu','Check the timetable for the next bus.'],
    ['weekday','ˈwiːkdeɪ','ngày trong tuần','I only study on weekdays.'],
    ['break','breɪk','giờ nghỉ','Let us take a short break.'],
    ['shift','ʃɪft','ca làm','She works the night shift.'],
    ['oversleep','ˌəʊvəˈsliːp','ngủ quá giấc','I overslept and missed the meeting.'] ]},
  { w:6, m:2, theme:'kế hoạch & dự định', src:'Oxford B1', items:[
    ['plan','plæn','kế hoạch','What is your plan for next month?'],
    ['intend','ɪnˈtend','dự định','I intend to finish this today.'],
    ['aim','eɪm','nhằm, mục tiêu','We aim to release on Friday.'],
    ['arrange','əˈreɪndʒ','sắp xếp','Can you arrange a call with them?'],
    ['postpone','pəˈspəʊn','hoãn','They postponed the meeting to Monday.'],
    ['confirm','kənˈfɜːm','xác nhận','Please confirm the time by email.'],
    ['book','bʊk','đặt trước','I booked a room for two nights.'],
    ['prepare','prɪˈpeə','chuẩn bị','I need to prepare for the test.'],
    ['expect','ɪkˈspekt','mong đợi','We expect ten people to come.'],
    ['decide','dɪˈsaɪd','quyết định','We decided to use a new tool.'] ]},
  { w:7, m:2, theme:'tính từ miêu tả người và việc', src:'Oxford B1–B2', warn:1, items:[
    ['reliable','rɪˈlaɪəbl','đáng tin cậy','He is a reliable member of the team.'],
    ['patient','ˈpeɪʃnt','kiên nhẫn','Please be patient, the build is slow.'],
    ['confident','ˈkɒnfɪdənt','tự tin','I feel confident about the test.'],
    ['careless','ˈkeələs','bất cẩn','That was a careless mistake.'],
    ['efficient','ɪˈfɪʃnt','hiệu quả','This method is more efficient.'],
    ['demanding','dɪˈmɑːndɪŋ','đòi hỏi cao','My new job is very demanding.'],
    ['challenging','ˈtʃælɪndʒɪŋ','đầy thử thách','The task was challenging but fun.'],
    ['straightforward','ˌstreɪtˈfɔːwəd','đơn giản, rõ ràng','The setup is straightforward.'],
    ['tedious','ˈtiːdiəs','tẻ nhạt','Writing tests is tedious but useful.'],
    ['promising','ˈprɒmɪsɪŋ','đầy hứa hẹn','The first results look promising.'] ]},
  { w:8, m:2, theme:'giao tiếp lịch sự', src:'Oxford B1 + mẫu câu', items:[
    ['Could you…?','kʊd juː','Bạn có thể…?','Could you send me the file, please?'],
    ['Would you mind…?','wʊd juː ˈmaɪnd','Bạn có phiền…?','Would you mind checking this code?'],
    ['I would appreciate it if…','əˈpriːʃieɪt','Tôi rất cảm kích nếu…','I would appreciate it if you could reply today.'],
    ['apologise','əˈpɒlədʒaɪz','xin lỗi','I apologise for the late reply.'],
    ['request','rɪˈkwest','yêu cầu (lịch sự)','I have a small request.'],
    ['permission','pəˈmɪʃn','sự cho phép','I need permission to deploy.'],
    ['suggest','səˈdʒest','gợi ý','I suggest we start on Monday.'],
    ['recommend','ˌrekəˈmend','khuyên dùng','I recommend this book.'],
    ['politely','pəˈlaɪtli','một cách lịch sự','He politely refused the offer.'],
    ['formal','ˈfɔːml','trang trọng','This email is too formal.'] ]},
  { w:9, m:3, theme:'giả định & phỏng đoán', src:'Oxford B1–B2', items:[
    ['suppose','səˈpəʊz','cho rằng','I suppose he is still working.'],
    ['assume','əˈsjuːm','giả định','Do not assume the data is clean.'],
    ['imagine','ɪˈmædʒɪn','tưởng tượng','Imagine you have no internet.'],
    ['likely','ˈlaɪkli','có khả năng','It is likely to rain tomorrow.'],
    ['unlikely','ʌnˈlaɪkli','không có khả năng','He is unlikely to come.'],
    ['probably','ˈprɒbəbli','có lẽ','She is probably at lunch.'],
    ['otherwise','ˈʌðəwaɪz','nếu không thì','Save your work, otherwise you will lose it.'],
    ['in case','ɪn ˈkeɪs','trong trường hợp','Take an umbrella in case it rains.'],
    ['provided that','prəˈvaɪdɪd ðæt','miễn là','I will help, provided that you ask early.'],
    ['as long as','əz ˈlɒŋ əz','miễn là','You can leave as long as the work is done.'] ]},
  { w:10, m:3, theme:'động từ hay dùng trong công việc', src:'Oxford B1 + BSL', items:[
    ['manage','ˈmænɪdʒ','quản lý','She manages a team of five.'],
    ['handle','ˈhændl','xử lý','I can handle this problem myself.'],
    ['review','rɪˈvjuː','xem lại, đánh giá','Please review my code today.'],
    ['approve','əˈpruːv','phê duyệt','The manager approved the plan.'],
    ['submit','səbˈmɪt','gửi, nộp','Submit the form before Friday.'],
    ['assign','əˈsaɪn','phân công','He assigned the task to me.'],
    ['monitor','ˈmɒnɪtə','theo dõi','We monitor the server every hour.'],
    ['implement','ˈɪmplɪment','triển khai','We will implement the change next week.'],
    ['maintain','meɪnˈteɪn','duy trì, bảo trì','Someone must maintain this old code.'],
    ['coordinate','kəʊˈɔːdɪneɪt','phối hợp','She coordinates work between two teams.'] ]},
  { w:11, m:3, theme:'quy trình & vận hành', src:'Oxford B2 + BSL', items:[
    ['process','ˈprəʊses','quy trình','The process has four steps.'],
    ['procedure','prəˈsiːdʒə','thủ tục','Follow the standard procedure.'],
    ['step','step','bước','The first step is easy.'],
    ['stage','steɪdʒ','giai đoạn','We are at an early stage.'],
    ['requirement','rɪˈkwaɪəmənt','yêu cầu','This is a basic requirement.'],
    ['standard','ˈstændəd','tiêu chuẩn','The code meets our standard.'],
    ['workflow','ˈwɜːkfləʊ','luồng công việc','Our workflow is clear now.'],
    ['approval','əˈpruːvl','sự phê duyệt','I am waiting for approval.'],
    ['compliance','kəmˈplaɪəns','sự tuân thủ','Compliance is not optional.'],
    ['efficiency','ɪˈfɪʃnsi','hiệu suất','The change improved efficiency.'] ]},
  { w:12, m:3, theme:'kể chuyện & tường thuật', src:'Oxford B1–B2', items:[
    ['meanwhile','ˈmiːnwaɪl','trong khi đó','I was coding. Meanwhile, she was testing.'],
    ['eventually','ɪˈventʃuəli','cuối cùng thì','The bug was eventually fixed.'],
    ['suddenly','ˈsʌdnli','bỗng nhiên','The server suddenly stopped.'],
    ['previously','ˈpriːviəsli','trước đó','I had previously worked there.'],
    ['afterwards','ˈɑːftəwədz','sau đó','We had lunch afterwards.'],
    ['at first','ət ˈfɜːst','lúc đầu','At first, I did not understand.'],
    ['by the time','baɪ ðə ˈtaɪm','đến lúc mà','By the time I arrived, they had left.'],
    ['shortly after','ˈʃɔːtli ˈɑːftə','ngay sau đó','He called shortly after the meeting.'],
    ['in the end','ɪn ði ˈend','cuối cùng','In the end, we chose the simple way.'],
    ['as soon as','əz ˈsuːn əz','ngay khi','Call me as soon as you finish.'] ]},
  { w:13, m:4, theme:'định nghĩa & giải thích', src:'Oxford B2', items:[
    ['define','dɪˈfaɪn','định nghĩa','Please define the problem clearly.'],
    ['refer to','rɪˈfɜː tə','đề cập đến','This number refers to the version.'],
    ['consist of','kənˈsɪst əv','gồm có','The team consists of four people.'],
    ['stand for','ˈstænd fɔː','là viết tắt của','API stands for Application Programming Interface.'],
    ['in other words','ɪn ˈʌðə wɜːdz','nói cách khác','It is slow. In other words, we must fix it.'],
    ['that is to say','ðæt ɪz tə ˈseɪ','tức là','It failed, that is to say, nothing worked.'],
    ['for instance','fər ˈɪnstəns','ví dụ','Use a cache, for instance Redis.'],
    ['namely','ˈneɪmli','cụ thể là','One thing is missing, namely the tests.'],
    ['such as','ˈsʌtʃ əz','chẳng hạn như','Tools such as Git are important.'],
    ['be known as','bi ˈnəʊn əz','được gọi là','This is known as a race condition.'] ]},
  { w:14, m:4, theme:'động từ tường thuật', src:'Oxford B1–B2', warn:1, items:[
    ['say','seɪ','nói (nội dung)','He said the work was done.'],
    ['tell','tel','kể cho ai','She told me about the change.'],
    ['explain','ɪkˈspleɪn','giải thích','Can you explain this error?'],
    ['mention','ˈmenʃn','nhắc đến','He mentioned a small problem.'],
    ['admit','ədˈmɪt','thừa nhận','She admitted that she was wrong.'],
    ['deny','dɪˈnaɪ','phủ nhận','He denied breaking the build.'],
    ['claim','kleɪm','khẳng định (chưa chắc đúng)','They claim the tool is faster.'],
    ['suggest','səˈdʒest','đề nghị','She suggested a different plan.'],
    ['insist','ɪnˈsɪst','khăng khăng','He insisted on doing it himself.'],
    ['warn','wɔːn','cảnh báo','I warned them about the risk.'] ]},
  { w:16, m:4, theme:'từ nối trong văn viết', src:'Oxford B2', items:[
    ['however','haʊˈevə','tuy nhiên','It is slow. However, it works.'],
    ['therefore','ˈðeəfɔː','vì vậy','The test failed, therefore we cannot ship.'],
    ['moreover','mɔːrˈəʊvə','hơn nữa','It is cheap. Moreover, it is fast.'],
    ['nevertheless','ˌnevəðəˈles','dù vậy','It was hard. Nevertheless, we finished.'],
    ['on the other hand','ɒn ði ˈʌðə hænd','mặt khác','It is fast. On the other hand, it costs more.'],
    ['in contrast','ɪn ˈkɒntrɑːst','trái lại','In contrast, the old version was simple.'],
    ['as a result','əz ə rɪˈzʌlt','kết quả là','As a result, the site was down.'],
    ['in addition','ɪn əˈdɪʃn','thêm vào đó','In addition, we added tests.'],
    ['consequently','ˈkɒnsɪkwəntli','do đó','Consequently, the release was late.'],
    ['for this reason','fə ðɪs ˈriːzn','vì lý do này','For this reason, we changed the plan.'] ]},
  { w:17, m:5, theme:'trạng từ chỉ thời gian nâng cao', src:'Oxford B1–B2', items:[
    ['already','ɔːlˈredi','đã rồi','I have already sent the email.'],
    ['still','stɪl','vẫn còn','He is still working on it.'],
    ['yet','jet','chưa (câu phủ định / nghi vấn)','I have not finished yet.'],
    ['recently','ˈriːsntli','gần đây','We recently moved to a new office.'],
    ['lately','ˈleɪtli','thời gian gần đây','I have been busy lately.'],
    ['so far','ˌsəʊ ˈfɑː','đến giờ','So far, everything works.'],
    ['ever since','ˌevə ˈsɪns','kể từ đó','Ever since the update, it is faster.'],
    ['by now','baɪ ˈnaʊ','đến lúc này','He should be here by now.'],
    ['no longer','nəʊ ˈlɒŋɡə','không còn nữa','This tool is no longer used.'],
    ['from then on','frəm ˈðen ɒn','từ đó trở đi','From then on, we wrote tests first.'] ]},
  { w:18, m:5, theme:'văn phong trang trọng', src:'Oxford B2 · nâng cấp từ thường', items:[
    ['obtain','əbˈteɪn','thu được — thay cho get','You can obtain the file from the server.'],
    ['require','rɪˈkwaɪə','cần — thay cho need','This job requires three years of experience.'],
    ['assist','əˈsɪst','hỗ trợ — thay cho help','Please assist the new team member.'],
    ['purchase','ˈpɜːtʃəs','mua — thay cho buy','We purchased ten new laptops.'],
    ['sufficient','səˈfɪʃnt','đủ — thay cho enough','We have sufficient time to test.'],
    ['demonstrate','ˈdemənstreɪt','chứng minh — thay cho show','The data demonstrates a clear trend.'],
    ['commence','kəˈmens','bắt đầu — thay cho start','The project will commence in May.'],
    ['inform','ɪnˈfɔːm','thông báo — thay cho tell','Please inform us of any change.'],
    ['attempt','əˈtempt','cố gắng — thay cho try','We attempted to fix it twice.'],
    ['regarding','rɪˈɡɑːdɪŋ','về việc — thay cho about','I have a question regarding the price.'] ]},
  { w:19, m:5, theme:'từ vựng học thuật cơ bản', src:'Oxford B2', items:[
    ['analyse','ˈænəlaɪz','phân tích','We analysed the user data.'],
    ['evaluate','ɪˈvæljueɪt','đánh giá','We must evaluate both options.'],
    ['significant','sɪɡˈnɪfɪkənt','đáng kể','There is a significant difference.'],
    ['factor','ˈfæktə','yếu tố','Cost is the main factor.'],
    ['approach','əˈprəʊtʃ','cách tiếp cận','We tried a new approach.'],
    ['evidence','ˈevɪdəns','bằng chứng','There is no evidence of a bug.'],
    ['concept','ˈkɒnsept','khái niệm','The concept is simple.'],
    ['impact','ˈɪmpækt','tác động','The change had a big impact.'],
    ['trend','trend','xu hướng','The trend is going up.'],
    ['consequence','ˈkɒnsɪkwəns','hệ quả','The consequence was a slow site.'] ]},
  { w:23, m:6, theme:'từ vựng học thuật nâng cao', src:'Oxford B2 → C1', items:[
    ['hypothesis','haɪˈpɒθəsɪs','giả thuyết','Our hypothesis was wrong.'],
    ['criterion','kraɪˈtɪəriən','tiêu chí','Speed is the main criterion.'],
    ['framework','ˈfreɪmwɜːk','khung, hệ quy chiếu','We built a simple framework for tests.'],
    ['implication','ˌɪmplɪˈkeɪʃn','hàm ý, hệ quả','This has serious implications for security.'],
    ['constraint','kənˈstreɪnt','ràng buộc, giới hạn','Time is our biggest constraint.'],
    ['correlation','ˌkɒrəˈleɪʃn','mối tương quan','There is a correlation between the two.'],
    ['substantial','səbˈstænʃl','đáng kể, lớn','We made substantial progress.'],
    ['inherent','ɪnˈhɪərənt','vốn có','Some risk is inherent in this design.'],
    ['subsequent','ˈsʌbsɪkwənt','tiếp theo sau','Subsequent tests all passed.'],
    ['comprehensive','ˌkɒmprɪˈhensɪv','toàn diện','We need a comprehensive review.'] ]},
  { w:24, m:6, theme:'cụm từ dùng trong bài luận', src:'mẫu câu B2', items:[
    ['It is widely believed that…','ˈwaɪdli bɪˈliːvd','Người ta tin rằng…','It is widely believed that remote work is here to stay.'],
    ['There is no doubt that…','daʊt','Không nghi ngờ gì rằng…','There is no doubt that testing saves time.'],
    ['This essay will argue that…','ˈɑːɡjuː','Bài này sẽ lập luận rằng…','This essay will argue that AI helps developers.'],
    ['One of the main reasons is…','ˈriːznz','Một trong những lý do chính là…','One of the main reasons is the low cost.'],
    ['It could be argued that…','ˈɑːɡjuːd','Có thể cho rằng…','It could be argued that both sides are right.'],
    ['A further point is that…','ˈfɜːðə','Một điểm nữa là…','A further point is that training takes time.'],
    ['On balance, …','ˈbæləns','Nhìn chung thì…','On balance, the benefits are greater than the costs.'],
    ['Despite this, …','dɪˈspaɪt','Dù vậy…','Despite this, many teams still do not test.'],
    ['To sum up, …','sʌm ˈʌp','Tóm lại…','To sum up, the plan is worth trying.'],
    ['In conclusion, …','kənˈkluːʒn','Kết luận là…','In conclusion, small daily steps work best.'] ]},
];

/* Tuần không có từ lõi riêng vì đã có bộ đóng, hoặc là tuần ôn */
const V_CLOSED = [
  { w:'4 – 5',   what:'80 động từ bất quy tắc',           goto:'irregular' },
  { w:'15',      what:'60 phrasal verbs',                 goto:'phrasal'   },
  { w:'20 · 25', what:'13 lỗi phát âm của người Việt',    goto:'pron'      },
  { w:'21',      what:'100 collocation',                  goto:'colloc'    },
  { w:'22 · 26', what:'tuần ôn — không có từ mới',        goto:''          },
];

/* Cách dựng thẻ Anki — một chiều, giữ hàng đợi ở ~78 thẻ/ngày */
const CARD_DEMO = {
  front:['deadline','/ˈdedlaɪn/ 🔊'],
  back:['hạn cuối','The deadline is Friday at five.','Hạn cuối là thứ Sáu, 5 giờ.'],
  rules:[
    'Một chiều duy nhất: từ → nghĩa. Không làm thẻ chiều ngược — 2 chiều là 140 thẻ/ngày, đúng cái bẫy bạn đã tránh khi hạ từ 15 xuống 10 từ.',
    'Bắt buộc có audio và IPA. Từ mà bạn không phát âm được thì khi nghe bạn cũng không nhận ra.',
    'Câu ví dụ phải ở mức A2: từ mới thì được, phần còn lại của câu phải là thứ bạn đọc trôi. Mọi câu trên trang này đã viết theo đúng luật đó — copy được thẳng vào thẻ.',
    '7 trong 10 từ mỗi ngày lấy theo TẦN SUẤT (Oxford 3000, lọc dải B1 + B2), chỉ 3 từ lấy theo chủ đề tuần. Cả khoá chỉ có 1.200 từ mới để đắp một khoảng trống 2.200 từ — độ phủ phải đi trước sở thích.',
    'Anki chỉ lo phần NHẬN BIẾT. Phần dùng được nằm ở chỗ khác: nói to 5 câu mỗi ngày, đoạn 80 từ mỗi T7, 15 phút AI voice.',
  ]
};

/* =========================================================
   THẺ CLOZE NGỮ PHÁP — 5 thẻ mỗi thứ Bảy, làm từ chính câu bạn viết sai.

   Vì sao phải có: từ vựng có Anki lo việc chống quên, ngữ pháp thì không.
   Một chủ điểm học ngày X được ôn thứ Bảy, kiểm tra cuối tháng, rồi không
   được chạm lại cho tới tuần 22 — bốn tháng cho mạo từ của tháng 1.
   5 thẻ/tuần đưa hàng đợi từ ~70 lên ~78 thẻ/ngày, vẫn nằm gọn trong 15'.
   Nếu làm 3 thẻ MỖI NGÀY thì thành ~105 thẻ và bạn sẽ bỏ Anki — cùng đúng
   cái bẫy đã tránh khi hạ từ 15 từ mới xuống 10.
   ========================================================= */
const CLOZE_DEMO = {
  front:['I am {{c1::a}} developer.','← câu SAI của chính bạn, đã sửa'],
  back:['a','Nghề nghiệp luôn có a / an.','Sai ngày 30.07 · tuần 1'],
  rules:[
    'Nguyên liệu là câu SAI của bạn trong tuần, không phải câu mẫu trong sách. Thẻ chỉ đáng làm khi nó bắt đúng lỗi bạn thật sự mắc.',
    'Khoét đúng MỘT chỗ — chỗ bạn đã sai. Khoét hai chỗ thì thành câu đố, không còn là phản xạ.',
    'Mặt sau ghi thêm một dòng luật ngắn và tuần đã học. Ba tháng sau bạn sẽ cần dòng đó.',
    'Đúng 5 thẻ mỗi thứ Bảy. Tuần nào sai ít hơn 5 câu thì lấy thêm từ sổ lỗi — sổ lỗi và Anki là hai đầu của cùng một việc.',
  ]
};
